import express, { json } from "express";
import cors from "cors";
import router from "./API/ApiV1";
import dotenv from 'dotenv';
dotenv.config();
const app=express();
app.use(json());
app.use(cors());
app.use("/api/v1",router);
app.listen(3001);