apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployments
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: backend-pods
  template:
    metadata:
      labels: 
        app: backend-pods
    spec:
      containers:  
        - name: backend
          image: shivamsaklani/tuneifybackend:latest
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          secret:
            secretName: backend-secret
