apiVersion: apps/v1
kind: Secret
metadata:
  name: frontend-secret
data:
  .env.local: TkVYVF9QVUJMSUNfQ2xpZW50SUQgPTkwOWY4MDIxZDI2NDQ0Njk4NGRkZmI4ZjJmN2FmN2NhCk5FWFRfUFVCTElDX0NsaWVudEtleSA9NDIyNmI0YWZhOGRlNGUzZjk0YzAzNTg1MDZkOTU3ODIKTkVYVF9QVUJMSUNfUmVkaXJlY3RVUkwgPWh0dHA6Ly9mcm9udGVuZHNlcnZpY2U6MzAwMAo=