apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  .env: Q2xpZW50SUQgPTkwOWY4MDIxZDI2NDQ0Njk4NGRkZmI4ZjJmN2FmN2NhCkNsaWVudEtleSA9NDIyNmI0YWZhOGRlNGUzZjk0YzAzNTg1MDZkOTU3ODIKUmVkaXJlY3RVUkwgPWh0dHA6Ly8xMjcuMC4wLjE6MzAwMC9hcGkvdjEvc3BvdGlmeS9hdXRoL2NhbGxiYWNrClNFU1NJT05fU0VDUkVUID1yYW5kb21zdHJpbmcK
